<?php
/********************************************************************************/
/* this file is part of: / diese Datei ist ein Teil von:                        */
/* tellmatic, the newslettermachine                                             */
/* tellmatic, die Newslettermaschine                                            */
/* 2006/7 by Volker Augustin, multi.art.studio Hanau                            */
/* Contact/Kontakt: mnl@multiartstudio.com                                      */
/* Homepage: www.tellmatic.de                                                   */
/* leave this header in file!                                                   */
/* diesen Header nicht loeschen!                                                */
/* check Homepage for Updates and more Infos                                    */
/* Besuchen Sie die Homepage fuer Updates und weitere Infos                     */
/********************************************************************************/

$_MAIN_DESCR="Dateimanager";
$_MAIN_MESSAGE.="";
$_MAIN_OUTPUT.='
<!--iframe src="'.$mnl_URL.'/'.$mnl_includedir.'/filemanager_bs.php" align="center"name="_filemanager" scrolling="no" marginheight="0px" marginwidth="0px" height="600" width="760"></iframe-->
<iframe src="'.$mnl_URL.'/'.$mnl_includedir.'/myftphp/myftphp_4.php" align="center"name="_filemanager" scrolling="no" marginheight="0px" marginwidth="0px" height="480" width="728" style="border:1px dashed grey; -moz-border-radius:2em 2em 2em 2em; padding: 4px"></iframe>
';
?>