<?php
/********************************************************************************/
/* this file is part of: / diese Datei ist ein Teil von:                        */
/* tellmatic, the newslettermachine                                             */
/* tellmatic, die Newslettermaschine                                            */
/* 2006/7 by Volker Augustin, multi.art.studio Hanau                            */
/* Contact/Kontakt: mnl@multiartstudio.com                                      */
/* Homepage: www.tellmatic.de                                                   */
/* leave this header in file!                                                   */
/* diesen Header nicht loeschen!                                                */
/* check Homepage for Updates and more Infos                                    */
/* Besuchen Sie die Homepage fuer Updates und weitere Infos                     */
/********************************************************************************/

$_MAIN_HELP=sprintf(___("Willkommen bei %s"),$ApplicationText);
//new Template
$_Tpl_Welcome=new mTemplate();
$_Tpl_Welcome->setTemplatePath($mnl_tplpath);
$_MAIN_OUTPUT.=$_Tpl_Welcome->renderTemplate("Welcome.html");
?>